name: SwitchUI
options:
  bundleIdPrefix: com.r3alcyb3r
targets:
  SwitchUI:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources # Put your SwitchUI and LocalJIT files here
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.r3alcyb3r.switchui
        # This part helps with JIT permissions
        CODE_SIGNING_ALLOWED: NO 
