name: SwitchUI
targets:
  SwitchUI:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Views
      - path: Sources
      - path: Assets.xcassets
    settings:
      # This links to the folder we just created
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.r3alcyb3r.SwitchUI
      SWIFT_VERSION: 5.0
