name: SwitchUI
options:
  bundleIdPrefix: com.r3alcyb3r
targets:
  SwitchUI:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      # Code Folder
      - Sources
      
      # Asset Catalog (Icons)
      - Assets.xcassets
      
      # Root Assets (Images)
      - smash.png
      - kart.png
      - party.png
      - header.png
      - source-logo.png
      
      # Root Assets (Sound)
      - click.mp3
      
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO 
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Entitlements.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.r3alcyb3r.switchui
        TARGETED_DEVICE_FAMILY: "1,2" # Support both iPhone and iPad
    info:
      plist:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
